apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-game-app
spec:
  replicas: 3  # Specify the number of replicas you want
  selector:
    matchLabels:
      app: tetris-game-app
  template:
    metadata:
      labels:
        app: tetris-game-app
    spec:
      containers:
      - name: tetris-game-app
        image: amanlabacr.azurecr.io/tetris-game-app:latest  # Use your ACR image
        ports:
        - containerPort: 8081  # Adjust the port if needed
